In [35]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier, export_text, plot_tree
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
import matplotlib as plt

### Load Diabetes Dataset

In [36]:
# Load dataset
df=pd.read_csv('Dataset of Diabetes .csv')
df

,ID,No_Pation,Gender,AGE,Urea,Cr,HbA1c,Chol,TG,HDL,LDL,VLDL,BMI,CLASS
0,502,17975,F,50,4.7,46,4.9,4.2,0.9,2.4,1.4,0.5,24.0,N
1,735,34221,M,26,4.5,62,4.9,3.7,1.4,1.1,2.1,0.6,23.0,N
2,420,47975,F,50,4.7,46,4.9,4.2,0.9,2.4,1.4,0.5,24.0,N
3,680,87656,F,50,4.7,46,4.9,4.2,0.9,2.4,1.4,0.5,24.0,N
4,504,34223,M,33,7.1,46,4.9,4.9,1.0,0.8,2.0,0.4,21.0,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,200,454317,M,71,11.0,97,7.0,7.5,1.7,1.2,1.8,0.6,30.0,Y
996,671,876534,M,31,3.0,60,12.3,4.1,2.2,0.7,2.4,15.4,37.2,Y
997,669,87654,M,30,7.1,81,6.7,4.1,1.1,1.2,2.4,8.1,27.4,Y
998,99,24004,M,38,5.8,59,6.7,5.3,2.0,1.6,2.9,14.0,40.5,Y
999,248,24054,M,54,5.0,67,6.9,3.8,1.7,1.1,3.0,0.7,33.0,Y

### Analyses the Dataset

In [37]:
# Check dataset
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ID         1000 non-null   int64
 1   No_Pation  1000 non-null   int64
 2   Gender     1000 non-null   str
 3   AGE        1000 non-null   int64
 4   Urea       1000 non-null   float64
 5   Cr         1000 non-null   int64
 6   HbA1c      1000 non-null   float64
 7   Chol       1000 non-null   float64
 8   TG         1000 non-null   float64
 9   HDL        1000 non-null   float64
 10  LDL        1000 non-null   float64
 11  VLDL       1000 non-null   float64
 12  BMI        1000 non-null   float64
 13  CLASS      1000 non-null   str
dtypes: float64(8), int64(4), str(2)
memory usage: 109.5 KB

In [38]:
df.head(10)

,ID,No_Pation,Gender,AGE,Urea,Cr,HbA1c,Chol,TG,HDL,LDL,VLDL,BMI,CLASS
0,502,17975,F,50,4.7,46,4.9,4.2,0.9,2.4,1.4,0.5,24.0,N
1,735,34221,M,26,4.5,62,4.9,3.7,1.4,1.1,2.1,0.6,23.0,N
2,420,47975,F,50,4.7,46,4.9,4.2,0.9,2.4,1.4,0.5,24.0,N
3,680,87656,F,50,4.7,46,4.9,4.2,0.9,2.4,1.4,0.5,24.0,N
4,504,34223,M,33,7.1,46,4.9,4.9,1.0,0.8,2.0,0.4,21.0,N
5,634,34224,F,45,2.3,24,4.0,2.9,1.0,1.0,1.5,0.4,21.0,N
6,721,34225,F,50,2.0,50,4.0,3.6,1.3,0.9,2.1,0.6,24.0,N
7,421,34227,M,48,4.7,47,4.0,2.9,0.8,0.9,1.6,0.4,24.0,N
8,670,34229,M,43,2.6,67,4.0,3.8,0.9,2.4,3.7,1.0,21.0,N
9,759,34230,F,32,3.6,28,4.0,3.8,2.0,2.4,3.8,1.0,24.0,N

In [39]:
# Numerical columns
num_cols=df.select_dtypes(include=[np.number]).drop(columns=['ID', 'No_Pation']).columns.to_list()
num_cols

['AGE', 'Urea', 'Cr', 'HbA1c', 'Chol', 'TG', 'HDL', 'LDL', 'VLDL', 'BMI']

In [40]:
# Describe all numerical columns without 'ID', 'No_Pation'
df[num_cols].describe()

,AGE,Urea,Cr,HbA1c,Chol,TG,HDL,LDL,VLDL,BMI
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,53.528000,5.124743,68.943000,8.281160,4.862820,2.349610,1.204750,2.609790,1.854700,29.578020
std,8.799241,2.935165,59.984747,2.534003,1.301738,1.401176,0.660414,1.115102,3.663599,4.962388
min,20.000000,0.500000,6.000000,0.900000,0.000000,0.300000,0.200000,0.300000,0.100000,19.000000
25%,51.000000,3.700000,48.000000,6.500000,4.000000,1.500000,0.900000,1.800000,0.700000,26.000000
50%,55.000000,4.600000,60.000000,8.000000,4.800000,2.000000,1.100000,2.500000,0.900000,30.000000
75%,59.000000,5.700000,73.000000,10.200000,5.600000,2.900000,1.300000,3.300000,1.500000,33.000000
max,79.000000,38.900000,800.000000,16.000000,10.300000,13.800000,9.900000,9.900000,35.000000,47.750000

### Drop 'ID' & 'No_Pation' columns

In [46]:
df=df.drop(columns=['ID', 'No_Pation'])
df.head()

  Gender  AGE  Urea  Cr  HbA1c  Chol   TG  HDL  LDL  VLDL   BMI CLASS
0      F   50   4.7  46    4.9   4.2  0.9  2.4  1.4   0.5  24.0     N
1      M   26   4.5  62    4.9   3.7  1.4  1.1  2.1   0.6  23.0     N
2      F   50   4.7  46    4.9   4.2  0.9  2.4  1.4   0.5  24.0     N
3      F   50   4.7  46    4.9   4.2  0.9  2.4  1.4   0.5  24.0     N
4      M   33   7.1  46    4.9   4.9  1.0  0.8  2.0   0.4  21.0     N

### Analyses the string columns & Data Cleaning

In [42]:
# Gender is a sting columns so check the unique value of gender
print(f'unique values:{df['Gender'].unique()}') 
print(f'number of unique values: {df['Gender'].nunique()}')
print(f'Value Count: {df['Gender'].value_counts()}')

unique values:<StringArray>
['F', 'M', 'f']
Length: 3, dtype: str
number of unique values: 3
Value Count: Gender
M    565
F    434
f      1
Name: count, dtype: int64

In [43]:
# Change data lowercase to uppercase
df['Gender']=df['Gender'].str.upper()
print(f'unique values:{df['Gender'].unique()}') 
print(f'number of unique values: {df['Gender'].nunique()}')
print(f'Value Count: {df['Gender'].value_counts()}')

unique values:<StringArray>
['F', 'M']
Length: 2, dtype: str
number of unique values: 2
Value Count: Gender
M    565
F    435
Name: count, dtype: int64

In [44]:
# CLASS is a sting columns so check the unique value of CLASS
print(f'unique values:{df['CLASS'].unique()}') 
print(f'number of unique values: {df['CLASS'].nunique()}')
print(f'Value Count: {df['CLASS'].value_counts()}')

unique values:<StringArray>
['N', 'N ', 'P', 'Y', 'Y ']
Length: 5, dtype: str
number of unique values: 5
Value Count: CLASS
Y     840
N     102
P      53
Y       4
N       1
Name: count, dtype: int64

In [45]:
#Remove whitespace 
df['CLASS']=df['CLASS'].str.strip()
print(f'unique values:{df['CLASS'].unique()}') 
print(f'number of unique values: {df['CLASS'].nunique()}')
print(f'Value Count: {df['CLASS'].value_counts()}')

unique values:<StringArray>
['N', 'P', 'Y']
Length: 3, dtype: str
number of unique values: 3
Value Count: CLASS
Y    844
N    103
P     53
Name: count, dtype: int64

### Identify the features and target values

In [ ]:
# Define feature and target columns
target='CLASS'
X=df.drop(columns=[target])
y=df[target]